/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author vinil
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        arquivoMenu = new javax.swing.JMenu();
        selectUser = new javax.swing.JMenuItem();
        login = new javax.swing.JMenuItem();
        saveExit = new javax.swing.JMenuItem();
        cadatrarMenu = new javax.swing.JMenu();
        cadastroAgencia = new javax.swing.JMenuItem();
        cadastroConta = new javax.swing.JMenuItem();
        cadastroFuncionario = new javax.swing.JMenuItem();
        cadastroCliente = new javax.swing.JMenuItem();
        removerMenu = new javax.swing.JMenu();
        removeAgencia = new javax.swing.JMenuItem();
        removeConta = new javax.swing.JMenuItem();
        removeFuncionario = new javax.swing.JMenuItem();
        removeCliente = new javax.swing.JMenuItem();
        editarMenu = new javax.swing.JMenu();
        editaAgencia = new javax.swing.JMenuItem();
        editaConta = new javax.swing.JMenuItem();
        editaFuncionario = new javax.swing.JMenuItem();
        editaCliente = new javax.swing.JMenuItem();
        transacaoMenu = new javax.swing.JMenu();
        transacaoSaque = new javax.swing.JMenuItem();
        transacaoDeposito = new javax.swing.JMenuItem();
        transacaoTranferencia = new javax.swing.JMenuItem();
        transacaoPagamento = new javax.swing.JMenuItem();
        ajudaMenu = new javax.swing.JMenu();
        ajudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco DBC");

        arquivoMenu.setText("Arquivo");

        selectUser.setText("Selecionar tipo do Usuário");
        selectUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserActionPerformed(evt);
            }
        });
        arquivoMenu.add(selectUser);

        login.setText("Logar");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        arquivoMenu.add(login);

        saveExit.setText("Salvar e Sair");
        arquivoMenu.add(saveExit);

        barraMenu.add(arquivoMenu);

        cadatrarMenu.setText("Cadastrar");

        cadastroAgencia.setText("Agência");
        cadastroAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAgenciaActionPerformed(evt);
            }
        });
        cadatrarMenu.add(cadastroAgencia);

        cadastroConta.setText("Conta");
        cadatrarMenu.add(cadastroConta);

        cadastroFuncionario.setText("Funcionario");
        cadatrarMenu.add(cadastroFuncionario);

        cadastroCliente.setText("Cliente");
        cadatrarMenu.add(cadastroCliente);

        barraMenu.add(cadatrarMenu);

        removerMenu.setText("Remover");

        removeAgencia.setText("Agência");
        removerMenu.add(removeAgencia);

        removeConta.setText("Conta");
        removerMenu.add(removeConta);

        removeFuncionario.setText("Funcionário");
        removerMenu.add(removeFuncionario);

        removeCliente.setText("Cliente");
        removerMenu.add(removeCliente);

        barraMenu.add(removerMenu);

        editarMenu.setText("Editar");

        editaAgencia.setText("Agência");
        editarMenu.add(editaAgencia);

        editaConta.setText("Conta");
        editarMenu.add(editaConta);

        editaFuncionario.setText("Funcionário");
        editarMenu.add(editaFuncionario);

        editaCliente.setText("Cliente");
        editarMenu.add(editaCliente);

        barraMenu.add(editarMenu);

        transacaoMenu.setText("Transação");

        transacaoSaque.setText("Saque");
        transacaoMenu.add(transacaoSaque);

        transacaoDeposito.setText("Depósito");
        transacaoMenu.add(transacaoDeposito);

        transacaoTranferencia.setText("Transferência");
        transacaoMenu.add(transacaoTranferencia);

        transacaoPagamento.setText("Pagamento");
        transacaoMenu.add(transacaoPagamento);

        barraMenu.add(transacaoMenu);

        ajudaMenu.setText("Ajuda");
        ajudaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaMenuActionPerformed(evt);
            }
        });

        ajudaSobre.setText("Sobre");
        ajudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaSobreActionPerformed(evt);
            }
        });
        ajudaMenu.add(ajudaSobre);

        barraMenu.add(ajudaMenu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectUserActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void cadastroAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAgenciaActionPerformed
        CadastroAgencia cadAgencia = new CadastroAgencia(this, true);
        cadAgencia.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        cadAgencia.setTitle("Cadastro de Agências");
        cadAgencia.setLocationRelativeTo(null);
        cadAgencia.setResizable(false);
        cadAgencia.setVisible(true);
    }//GEN-LAST:event_cadastroAgenciaActionPerformed

    private void ajudaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaMenuActionPerformed
        
    }//GEN-LAST:event_ajudaMenuActionPerformed

    private void ajudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaSobreActionPerformed
        JOptionPane.showMessageDialog(null, "Bem vindo ao Banco DBC, selecione o tipo de usuário e depois faça o login.");
    }//GEN-LAST:event_ajudaSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TelaPrincipal().setVisible(true);
                TelaPrincipal telaPrincipal = new TelaPrincipal();
                telaPrincipal.setLocationRelativeTo(null);
                telaPrincipal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajudaMenu;
    private javax.swing.JMenuItem ajudaSobre;
    private javax.swing.JMenu arquivoMenu;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem cadastroAgencia;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroConta;
    private javax.swing.JMenuItem cadastroFuncionario;
    private javax.swing.JMenu cadatrarMenu;
    private javax.swing.JMenuItem editaAgencia;
    private javax.swing.JMenuItem editaCliente;
    private javax.swing.JMenuItem editaConta;
    private javax.swing.JMenuItem editaFuncionario;
    private javax.swing.JMenu editarMenu;
    private javax.swing.JMenuItem login;
    private javax.swing.JMenuItem removeAgencia;
    private javax.swing.JMenuItem removeCliente;
    private javax.swing.JMenuItem removeConta;
    private javax.swing.JMenuItem removeFuncionario;
    private javax.swing.JMenu removerMenu;
    private javax.swing.JMenuItem saveExit;
    private javax.swing.JMenuItem selectUser;
    private javax.swing.JMenuItem transacaoDeposito;
    private javax.swing.JMenu transacaoMenu;
    private javax.swing.JMenuItem transacaoPagamento;
    private javax.swing.JMenuItem transacaoSaque;
    private javax.swing.JMenuItem transacaoTranferencia;
    // End of variables declaration//GEN-END:variables
}
